In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
import warnings
warnings.filterwarnings('ignore')
from sklearn import linear_model

In [38]:
ecommerce = pd.read_csv('/content/ecommerce-product-reviews.csv')
ecommerce

                                                 review     label
0                      Law simply actually race it run.  positive
1     Fish help admit group gun real. Trial road tel...   neutral
2     Life standard score charge assume law.\nStatio...  positive
3     And perform edge data sea first. Something rev...   neutral
4     Animal interview huge activity some health deb...  negative
...                                                 ...       ...
4995  Man continue board. Mother drive tree actually...   neutral
4996  Could this poor a race senior free. Respond co...  positive
4997  Special draw sit conference end knowledge focu...  negative
4998  Write thank enjoy effect. Light home hospital ...   neutral
4999  Beautiful on tonight and. Million civil sense ...  negative

[5000 rows x 2 columns]

In [6]:
ecommerce.head()

                                              review     label
0                   Law simply actually race it run.  positive
1  Fish help admit group gun real. Trial road tel...   neutral
2  Life standard score charge assume law.\nStatio...  positive
3  And perform edge data sea first. Something rev...   neutral
4  Animal interview huge activity some health deb...  negative

In [50]:
model = make_pipeline(TfidfVectorizer(), MultinomialNB())
model

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('multinomialnb', MultinomialNB())])

In [51]:
# 2. Split data (X = reviews, y = labels)
X_train, X_test, y_train, y_test = train_test_split(ecommerce['review'], ecommerce['label'], test_size=0.2)
X_train, X_test, y_train, y_test

(3803    Be recently sign establish yourself.\nYeah com...
 734     Statement minute natural result. Can probably ...
 4952    They character enjoy employee public offer. Ba...
 1455    Reveal would month ability. Mouth president bo...
 4959    Door character guess provide employee final wo...
                               ...
 4549    Stage dinner professor process woman result. C...
 3243    Need rest name different religious month. Inst...
 2165    Civil analysis rate base research office. Brot...
 1724    Thousand world executive nice back produce.\nW...
 802     Bed share couple. Opportunity focus performanc...
 Name: review, Length: 4000, dtype: object,
 2949    Avoid walk according professional may soldier....
 4289    They carry some travel defense. Yeah together ...
 4492    Become buy home treat. Color require message a...
 4219    Film hold keep economy agency star close hold....
 1964    Daughter strong research agency important stat...
                               ...
 3751    Blue better opportunity everyone matter commun...
 4243    Out sign front peace force. Once detail rise. ...
 4927    Suffer wall necessary wish who. Speech woman h...
 597     Himself direction politics election light iden...
 638     Behavior whom nice. Hear record should who go ...
 Name: review, Length: 1000, dtype: object,
 3803    positive
 734     positive
 4952     neutral
 1455    positive
 4959    positive
           ...
 4549     neutral
 3243     neutral
 2165    negative
 1724    positive
 802      neutral
 Name: label, Length: 4000, dtype: object,
 2949     neutral
 4289    negative
 4492    positive
 4219    positive
 1964    positive
           ...
 3751    negative
 4243    positive
 4927    negative
 597      neutral
 638     positive
 Name: label, Length: 1000, dtype: object)

In [54]:
model = make_pipeline(TfidfVectorizer(), linear_model.LogisticRegression())
model

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('logisticregression', LogisticRegression())])

In [57]:
#  Train and Score
model.fit(X_train, y_train)

Pipeline(steps=[('tfidfvectorizer', TfidfVectorizer()),
                ('logisticregression', LogisticRegression())])

In [58]:
print(model.score(X_test, y_test))

0.338